### PR TITLE
Zoom automation

### PR DESCRIPTION
**Pull request by chriswedgwood**
This will iterate over data in
a file meetings.csv(test one provided)
and using pyautogui. I am not adding this to
the requirements file as it is not needed for
the website.

to run:
pip install pyautogui
python main.py

more instractions in main.py

### CODE REVIEW

**Comment by tintinnabulate** [comment]
Hi @chriswedgwood  - could we put these in a separate repository, but under the same GitHub organisation? That seems like a good way to keep the website repo uncluttered & clean.

**Review by tintinnabulate — CHANGES_REQUESTED** [review]
Hi @chriswedgwood - could we put these in a separate repository, but under the same GitHub organisation? That seems like a good way to keep the website repo uncluttered & clean.

**Comment by chriswedgwood** [comment]
Yes good idea

**Comment by tintinnabulate** [comment]
@chriswedgwood  I started having a play with it, here https://github.com/tintinnabulate/zoom-meeting-checker

Managed to get it working with some tweaks.

**Comment by chriswedgwood** [comment]
Cool let's get it into aalondon repo👍

**Comment by chriswedgwood** [comment]
Actually Ill put my version in and you can merge your changes

**Pull request closed without merging**
