### PR TITLE
Meetingguide endpoint

### PR DESCRIPTION
**Pull request by chriswedgwood**
This creates an api endpoint that will ultimately be used for sharing data with the meeting guide app(https://www.aa.org/pages/en_US/meeting-guide)

The spec for the api is here https://github.com/code4recovery/spec

the api validator is here: https://meetingguide.org/validate

We need to get this onto staging so we can test endpoint against their validator

### CODE REVIEW

**Comment by chriswedgwood** [comment]
[Create feed for meeting guide of physical meetings](https://trello.com/c/N5c5G15Z/59-create-feed-for-meeting-guide-of-physical-meetings)

**Comment by chriswedgwood** [comment]
[Create feed for meeting guide of physical meetings](https://trello.com/c/N5c5G15Z/59-create-feed-for-meeting-guide-of-physical-meetings)

**Comment by chriswedgwood** [comment]
[Create feed for meeting guide of physical meetings](https://trello.com/c/N5c5G15Z/59-create-feed-for-meeting-guide-of-physical-meetings)

**Comment by chriswedgwood** [comment]
[Create feed for meeting guide of physical meetings](https://trello.com/c/N5c5G15Z/59-create-feed-for-meeting-guide-of-physical-meetings)

**Comment by chriswedgwood** [comment]
[Create feed for meeting guide of physical meetings](https://trello.com/c/N5c5G15Z/59-create-feed-for-meeting-guide-of-physical-meetings)

**Comment by tintinnabulate** [comment]
Exciting stuff. If we pass the validator then we can use this as a template for the API for alcoholics-anonymous.org.uk !

Note that In November 2018 I asked Josh (dev for MeetingGuide) if he'd accept an unofficial endpoint of the UK's meetings. His response:

> We'd love to add UK meetings of course, but we only accept data from orgs that want to participate. The only way to add these meetings would be to get them to agree.

**Review by tintinnabulate — APPROVED** [review]
LGTM

**Comment by chriswedgwood** [comment]
Yes I think we will have to go down the route of the two London Regions wanting it so its an official request.

**Pull request merged**
