### PR TITLE
Cleanup of Reflections #218

### PR DESCRIPTION
**Pull request by tintinnabulate**
* Split up separate words that were joined by commas (e.g.
"serenity,and" becomes "serenity, and")

* Split up separate words that were joined by periods (e.g.
"serenity.The" becomes "serenity. The")

* Other similar edits to the above.

* Fix typos for rest of November and all of December.

### CODE REVIEW

**Comment by tintinnabulate** [comment]
Note that this only fixes up-to-and-including December 31^st^. I plan on doing January etc. in chunks.

**Review by chriswedgwood — APPROVED** [review]

**Comment by tintinnabulate** [comment]
@chriswedgwood I think we need to re-run the migration somehow to pick up the new JSON file. 

I've just looked at staging, and it hasn't picked up these edits.

**Comment by chriswedgwood** [comment]
We can restore staging to prod and re run deploy

Or we can create a new migration

**Comment by tintinnabulate** [comment]
> We can restore staging to prod and re run deploy
> Or we can create a new migration

@chriswedgwood  Creating a new migration is best, IMO, because we may need to do this sort of thing again and it would be good to have an example checked into the repository.

**Comment by chriswedgwood** [comment]
Cool duplicating the last migration in that app will do it

**Pull request merged**
